//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSWindowController.h"

//#import "ConversionDelegate.h"

@class ConversionController, LCDController, NSButton, NSDictionary, NSLayoutConstraint, NSMenu, NSMenuItem, NSMutableArray, NSMutableDictionary, NSSavePanel, NSString, PaperTapeController, SpeechController;

//@interface CalculatorController : NSWindowController <ConversionDelegate>
@interface CalculatorController : NSObject
{
    NSMenu *mConvertMenu;
    NSMenu *mPrecisionMenu;
    NSButton *mClearTapeButton;
    PaperTapeController *mTapeWindow;
    SpeechController *mSpeechController;
    NSMenuItem *mRecentConversionsMenuItem;
    NSMenu *mRecentConversionsMenu;
    NSMenuItem *mClearRecentConversionsMenuItem;
    NSMenuItem *mRPNMenuItem;
    NSMenuItem *mSeparatorsItem;
    NSMenuItem *mIEEEItem;
    NSMenuItem *mRPNContextualMenuItem;
    NSMenuItem *mCloseMenuItem;
    NSMenu *mDebugMenu;
    NSLayoutConstraint *parentLCDHeight;
    NSLayoutConstraint *parentLCDWidth;
    LCDController *mLCD;
    NSDictionary *mSpeakableItemsDict;
    NSMenu *_ViewsMenu;
    BOOL mZoomed;
    int mPreviousWindowSize;
    NSSavePanel *mSavePanel;
    NSMutableArray *mPlugins;
    BOOL g_RPN;
    ConversionController *_conversionController;
    NSString *__PreviousViewKey;
    id __CurrentView;
    NSMutableDictionary *__ViewControllerDict;
    NSMutableArray *__OrderedControllerNames;
    int __BackEndMode;
}

//+ (void)restoreWindowWithIdentifier:(id)arg1 state:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)adjustWindowPosition;
- (void)applicationDidFinishLaunching:(id)arg1;
- (BOOL)applicationShouldOpenUntitledFile:(id)arg1;
- (BOOL)applicationShouldTerminateAfterLastWindowClosed:(id)arg1;
- (void)awakeFromNib;
- (void)clearRecentConversionsMenu:(id)arg1;
- (void)convert:(id)arg1;
- (void)copy:(id)arg1;
- (void)dealloc;
- (void)dumpStack:(id)arg1;
- (void)handleConversion:(id)arg1;
- (id)init;
- (void)initItemsWithStoredDefaults;
- (BOOL)languageIsFrench;
- (id)lcd:(id)arg1;
- (void)loadView:(id)arg1;
- (id)localizedValueForString:(id)arg1;
- (void)menuViewSelectionDidChange:(id)arg1;
- (void)openExpressionSyntaxHelp:(id)arg1;
- (id)pathsToPlugins;
- (void)populateConvertMenu;
- (void)prepareConversion:(id)arg1;
- (id)previousView:(id)arg1;
- (BOOL)readyForConversion;
- (void)recentConversionsHaveChanged;
- (void)sendDataToCalcEngine:(id)arg1;
- (void)setBackEndMode:(int)arg1;
- (void)setCurrentView:(id)arg1;
- (void)setPrecision:(id)arg1;
- (void)showAbout:(id)arg1;
- (void)toggleRPNMode:(id)arg1;
- (void)toggleSeparators:(id)arg1;
- (void)updateRecentConversionsMenu;
- (BOOL)validateMenuItem:(id)arg1;
- (void)window:(id)arg1 willEncodeRestorableState:(id)arg2;
- (void)windowDidBecomeKey:(id)arg1;
- (void)windowDidLoad;
- (void)windowDidMove:(id)arg1;
- (void)windowDidUpdate:(id)arg1;
- (BOOL)windowShouldZoom:(id)arg1 toFrame:(struct CGRect)arg2;
- (void)windowWillClose:(id)arg1;
- (struct CGSize)windowWillResize:(id)arg1 toSize:(struct CGSize)arg2;
- (void)writeObject:(id)arg1 toPasteboard:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

