//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

//#import "NSCoding.h"

@interface GameState : NSObject <NSCoding>
{
    BOOL fastFlagMode;
    int difficulty;
    int row;
    int column;
    int mines;
    BOOL suppression;
    BOOL isSoundON;
    BOOL isGameCenterON;
    int robot;
    int sensitivity;
    BOOL fullgame;
    int beginner1;
    int beginner2;
    int beginner3;
    int intermediate1;
    int intermediate2;
    int intermediate3;
    int expert1;
    int expert2;
    int expert3;
    BOOL isRedTutorialShown;
    BOOL isGreenTutorialShown;
    int lastScore;
    int lastRanking;
    float lastPercent;
    BOOL lastWin;
}

+ (id)alloc;
+ (id)sharedInstance;
@property int beginner1; // @synthesize beginner1;
@property int beginner2; // @synthesize beginner2;
@property int beginner3; // @synthesize beginner3;
@property int column; // @synthesize column;
@property int difficulty; // @synthesize difficulty;
- (void)encodeWithCoder:(id)arg1;
@property int expert1; // @synthesize expert1;
@property int expert2; // @synthesize expert2;
@property int expert3; // @synthesize expert3;
@property BOOL fastFlagMode; // @synthesize fastFlagMode;
@property BOOL fullgame; // @synthesize fullgame;
- (id)init;
- (id)initWithCoder:(id)arg1;
@property int intermediate1; // @synthesize intermediate1;
@property int intermediate2; // @synthesize intermediate2;
@property int intermediate3; // @synthesize intermediate3;
@property BOOL isGameCenterON; // @synthesize isGameCenterON;
@property BOOL isGreenTutorialShown; // @synthesize isGreenTutorialShown;
@property BOOL isRedTutorialShown; // @synthesize isRedTutorialShown;
@property BOOL isSoundON; // @synthesize isSoundON;
@property float lastPercent; // @synthesize lastPercent;
@property int lastRanking; // @synthesize lastRanking;
@property int lastScore; // @synthesize lastScore;
@property BOOL lastWin; // @synthesize lastWin;
@property int mines; // @synthesize mines;
@property int robot; // @synthesize robot;
@property int row; // @synthesize row;
- (void)save;
@property int sensitivity; // @synthesize sensitivity;
@property BOOL suppression; // @synthesize suppression;

@end

