//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "MQAIOToolsControllerV5.h"

//#import "MQEventForwardViewDelegate.h"
//#import "MQFaceButtonDelegate.h"
//#import "MQSwitchButtonDelegate.h"
//#import "NSMenuDelegate.h"

@class MQFaceButton, MQMenuButton, MQSwitchButton, NSButton, NSString, TXHoverButton;

//@interface MQAIOChatTootKitViewController : MQAIOToolsControllerV5 <NSMenuDelegate, MQEventForwardViewDelegate, MQFaceButtonDelegate, MQSwitchButtonDelegate>
@interface MQAIOChatTootKitViewController : NSViewController
{
    int _currentMode;
    MQFaceButton *_faceBtn;
    TXHoverButton *_grabBtn;
    TXHoverButton *_shakeBtn;
    TXHoverButton *_pictureBtn;
    TXHoverButton *_historyBtn;
    TXHoverButton *_disruptBtn;
    NSButton *_switchBtn;
    TXHoverButton *_fileBtn;
    TXHoverButton *_pttBtn;
    MQMenuButton *_avBtn;
}

@property(readonly) MQMenuButton *avBtn;
- (id)buttonOfClass:(Class)arg1;
- (id)currentBlockStateDescription;
- (unsigned long long)currentBlockStateMentItemIndex;
- (void)dealloc;
- (void)didMouseDown:(id)arg1;
@property(readonly) TXHoverButton *disruptBtn;
@property(readonly) MQFaceButton *faceBtn;
- (struct CGPoint)faceButtonPosition;
@property(readonly) TXHoverButton *fileBtn;
@property(readonly) TXHoverButton *grabBtn;
- (void)handleBlockStatusDidChange:(int)arg1 notification:(id)arg2;
- (void)handleDiscussEventNotification:(id)arg1;
- (void)handleGroupEventNotification:(id)arg1;
- (void)handleIMInfoEventNotification:(id)arg1;
@property(readonly) TXHoverButton *historyBtn;
- (void)hoverShowFaceBtn;
- (id)init;
- (void)insertCustomFace:(id)arg1;
- (void)insertSyetemFacesAtIndex:(int)arg1;
- (BOOL)isCurrentSessionInBlockState;
- (BOOL)isCurrentSessionInNoAlertState;
- (void)menuNeedsUpdate:(id)arg1;
- (int)modeOfSession:(id)arg1;
- (void)onBlock:(id)arg1;
- (void)onChangeStateButton:(id)arg1 state:(int)arg2;
- (void)onClickSwitchButton:(id)arg1;
- (void)onFaceButtonClick;
- (void)onGrabScreen:(id)arg1;
- (void)onMsgRecord:(id)arg1;
- (void)onPicture:(id)arg1;
- (id)onPopUpMenuWithEvent:(id)arg1 forView:(id)arg2;
- (void)onShakeWindow:(id)arg1;
@property(readonly) TXHoverButton *pictureBtn;
- (void)setConstraintsForButton:(id)arg1;
- (void)setIsVoiceInputting:(BOOL)arg1;
- (void)setSessionId:(id)arg1;
- (void)setToolKitEnabled:(BOOL)arg1;
- (void)setupUI:(int)arg1;
@property(readonly) TXHoverButton *shakeBtn;
@property(readonly) MQSwitchButton *switchBtn;
- (id)topAlignView:(id)arg1 andView:(id)arg2;
- (void)updateBlockButton;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) TXHoverButton *pttBtn;
@property(readonly) Class superclass;

@end

